export const domesticDomains = [
  // 搜索引擎
  'baidu.com',
  'sogou.com',
  'so.com',
  'sm.cn',
  'chinaso.com',

  // 社交媒体
  'weibo.com',
  'douyin.com',
  'xiaohongshu.com',
  'zhihu.com',
  'douban.com',
  'tieba.baidu.com',
  'weixin.qq.com',
  'qzone.qq.com',
  'kuaishou.com',
  'hupu.com',
  'tianya.cn',
  'mop.com',

  // 电商平台
  'taobao.com',
  'jd.com',
  'tmall.com',
  'pinduoduo.com',
  'vip.com',
  'suning.com',
  'dangdang.com',
  'gome.com.cn',
  'mogujie.com',
  'meituan.com',
  'ele.me',
  'kaola.com',
  'yanxuan.163.com',
  'dewu.com',
  '1688.com',

  // 视频平台
  'bilibili.com',
  'iqiyi.com',
  'youku.com',
  'v.qq.com',
  'mgtv.com',
  'acfun.cn',
  'pptv.com',
  'le.com',
  'sohu.com',
  'cctv.com',
  'huya.com',
  'douyu.com',

  // 新闻门户
  'qq.com',
  '163.com',
  'sina.com.cn',
  'sohu.com',
  'ifeng.com',
  'people.com.cn',
  'xinhuanet.com',
  'chinadaily.com.cn',
  'huanqiu.com',
  'thepaper.cn',
  'jiemian.com',
  '36kr.com',
  'huxiu.com',
  'tmtpost.com',

  // 金融服务
  'alipay.com',
  'icbc.com.cn',
  'ccb.com',
  'boc.cn',
  'abchina.com',
  'cmbchina.com',
  'bankofchina.com',
  'spdb.com.cn',
  'ecitic.com',
  'eastmoney.com',
  'hexun.com',
  'jrj.com.cn',
  'cnstock.com',

  // 教育学习
  'cnki.net',
  'xueersi.com',
  'hujiang.com',
  'koolearn.com',
  'icourse163.org',
  'xuetangx.com',
  'imooc.com',
  'w3school.com.cn',
  'runoob.com',

  // 生活服务
  'dianping.com',
  '58.com',
  'ganji.com',
  'baixing.com',
  'fang.com',
  'lianjia.com',
  'ke.com',
  'anjuke.com',
  'autohome.com.cn',
  'pcauto.com.cn',
  'xcar.com.cn',
  'bitauto.com',

  // 工具服务
  'baidu.com',
  'dingtalk.com',
  'wps.cn',
  'youdao.com',
  'xunlei.com',
  '360.cn',
  'duba.com',

  // 开发技术
  'csdn.net',
  'gitee.com',
  'oschina.net',
  'cnblogs.com',
  'segmentfault.com',
  'juejin.cn',
  'v2ex.com',
  'iteye.com',

  // 音乐平台
  'music.163.com',
  'y.qq.com',
  'kugou.com',
  'kuwo.cn',
  'xiami.com',

  // 游戏平台
  'store.steampowered.com',
  '4399.com',
  '7k7k.com',
  '17173.com',
  'duowan.com',
];

export const internationalDomains = [
  // 社交媒体
  'facebook.com',
  'instagram.com',
  'twitter.com',
  'linkedin.com',
  'tiktok.com',
  'snapchat.com',
  'pinterest.com',
  'reddit.com',
  'discord.com',
  'telegram.org',
  'whatsapp.com',
  'tumblr.com',
  'flickr.com',
  'quora.com',
  'vk.com',
  'myspace.com',
  'meetup.com',
  'tagged.com',
  'badoo.com',
  'mastodon.social',

  // 视频平台
  'youtube.com',
  'netflix.com',
  'twitch.tv',
  'vimeo.com',
  'dailymotion.com',
  'hulu.com',
  'hbo.com',
  'disney.com',
  'primevideo.com',
  'peacocktv.com',
  'paramount.com',
  'crunchyroll.com',
  'funimation.com',
  'ted.com',

  // 搜索引擎
  'google.com',
  'bing.com',
  'yahoo.com',
  'duckduckgo.com',
  'yandex.com',
  'ask.com',
  'aol.com',
  'baidu.com',
  'ecosia.org',
  'wolframalpha.com',

  // 电商购物
  'amazon.com',
  'ebay.com',
  'walmart.com',
  'shopify.com',
  'etsy.com',
  'aliexpress.com',
  'wish.com',
  'target.com',
  'bestbuy.com',
  'homedepot.com',
  'lowes.com',
  'costco.com',
  'macys.com',
  'nordstrom.com',
  'ikea.com',
  'wayfair.com',
  'newegg.com',
  'overstock.com',
  'zappos.com',
  'sephora.com',

  // 新闻媒体
  'cnn.com',
  'bbc.com',
  'nytimes.com',
  'theguardian.com',
  'washingtonpost.com',
  'wsj.com',
  'usatoday.com',
  'reuters.com',
  'bloomberg.com',
  'forbes.com',
  'businessinsider.com',
  'techcrunch.com',
  'theverge.com',
  'wired.com',
  'arstechnica.com',
  'engadget.com',
  'gizmodo.com',
  'mashable.com',
  'buzzfeed.com',
  'vice.com',

  // 工具服务
  'gmail.com',
  'outlook.com',
  'yahoo.com',
  'protonmail.com',
  'dropbox.com',
  'drive.google.com',
  'onedrive.com',
  'box.com',
  'mega.nz',
  'wetransfer.com',
  'zoom.us',
  'skype.com',
  'slack.com',
  'teams.microsoft.com',
  'notion.so',
  'evernote.com',
  'trello.com',
  'asana.com',

  // 开发技术
  'github.com',
  'stackoverflow.com',
  'gitlab.com',
  'bitbucket.org',
  'codecademy.com',
  'udemy.com',
  'coursera.org',
  'edx.org',
  'khan-academy.org',
  'w3schools.com',

  // 音乐平台
  'spotify.com',
  'apple.com',
  'soundcloud.com',
  'pandora.com',
  'deezer.com',
  'tidal.com',
  'bandcamp.com',
  'last.fm',

  // 金融服务
  'paypal.com',
  'stripe.com',
  'coinbase.com',
  'binance.com',
  'robinhood.com',
  'chase.com',
  'bankofamerica.com',
  'wellsfargo.com',
  'citibank.com',
  'americanexpress.com',
];